language: ruby
cache: bundler
rvm:
- 2.1
script: ./bin/cibuild
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAI6APVDWJXWFVTR3A
  secret_access_key:
    secure: f5AU/0W/vnq460lOL1aVGAkStzjQ0G+pxmmlDP6//uigMoPwzqKZXE+E1sXtYkhfAuhmRERolEswmsnpxq12aGqkHtG+I+JXQWkgBE40HtbRSn6k08YiwwbKhGG1VlTD51zle8cY+xg3TlLkaW+nOe17LnHXOmx/1qmKmqy7AYoPR9Fnc4w2ymnZQnie9Bj3e+mBIvY3ErB2ilhFJDkBD3QpEbcCO4a4ahIpz5An8m1DG5Oy+eou3cM7pABaTeXR4Fpd6hc2BggXoIKg8+K6FrEqtBEZLAsB0le8RBN2z430+la2wFe3vyvBGu5h2Cgv9/Bx+lTgPp8oj/nBdvy4eGSQx/uqSgX1nI8MvzF2a3RHwqLGDXEJbzsqZEKxvpTOvib7SFD0oyAUHlR771VdO5u++7zr2OJa4TCtKmnfLE9skM4ABVoIe4Gzlgeiw3l/Q9H1+YCC3RBykouj3MlQ5SWYIlKM0NkPR+7+5vySEH16JvBVHOUdFxhpll9LtQDN8GCTETx0F4SrnPDO7PR0Unc/NNIIedj/iVVTLKsAHJ3jFYbsXydCnW2bYUumqhErq77ebTC+N3fzymCb2v0kmI8ZOgUOG6fsdw5Ws4d1kyawZersDmm61E1I/HfY5Zf+X5yr+QAywhtVc6B1uFyzWgdIybQEOI+fetYVpeda6BQ=
  bucket: www.howell.io
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    repo: dehowell/howellio-jekyll
