language: ruby
rvm:
- 2.1
script: ./script/cibuild
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJDMXEVCIGD74HLWA
  secret_access_key:
    secure: HALR3MaG17QKFwQiMKwpremO0VlY/mhF/D8J05DnUXmbUtZIx6ypdglWCt6l+MJbC67I4FFyPhGIeShrqjd0wARJTsw4ZfmIClyonfwHkmwgyfDW2fAm9t4rZdb04KQ0Iw/GqqNIMEorVKd8LXJJZC4adDIgnRlMNi0myiPCRroSkjUkQaytEDS/5AK7KDJ82C5znS/lLRFAhSs/QDR+ERvGIh+30wvWmMh5YNR4IheNLn++pqSfBH/wOsoDjkSLTwknQTDM3wsHAzDrjh/YJV+K92aXhL3iYd6yjT1JkiPaPA5SOZ/vNZd3LOdVHVOZ7hwBe8Cp5rjcfXomM8bf2QnNd3JKGQ4U7MfGklhw+bPC/XMLXI2oarEhv15+/I0/wIQiMCjj0CHJmXz/vjhkNZ+5UB6N1ywWcCsa8F0d/IMg/IIWWNu/E2AErD/afn0vHOVHaAtF5U4mu6d5PYBx+hY+rc5W2xt1OljZEIIeiyY/upQPzaHtle02T798vmHVjggwNbr1f32JLzMBc5vQMaYbilFtCWG0m1OykObv71Bams0ARvuonLbx/7Ta8P9iPO/p3GMdVVNvOylzl9TIq4nVFIGY3K1Szb4s4PuFsgcMBGDYdO4ObKRC9fZcxScfmP+dPdQk/qJUOZ7nesbk2PCbAZfP6yFFouHh2s4RTF4=
  bucket: www.howell.io
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    repo: dehowell/dehowell.github.io
