language: ruby
rvm:
- 2.1
script: ./script/cibuild
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAIESDHAXA54DNAPAA
  secret_access_key:
    secure: u2vcDGRZx4vgtLMS4BVpmCeLL1I1FVF7keLZRaStG3dJaUhtUhWHp1t3ySCy48xYKamSygYQ32xrXV4oI5VE7KkW1z4mNEetWJslgAQxQnxyPTygyVlgXVytLKpBa5fUYSoDSZX5KE2bP5yD7kVoGzO9oaqSLgxgjTDemZeCdULy+jMGvnRqhPRLNNB4K7CDYCe+Re25A3euBYHEQWXyliwiPENmew/d2Iv3b2ymuc1cVC2753OXl7MAljwjfcLrbI+SyPUutieZvrBqRA0dRdfVMZ273FMo6kAw+z45fHIJ4yw5eQJqGUlmlRMCcRx2ASuP2xGCMU0Ac8ybMGb2PFddUTHJg/q0Hq0p68i7wxFEj6Fj622hdrJ3ms79l1pNSsDTBubLH0pti79+IIdTYKd/eZO2ZW5USVEakNzcepwGO8X1q5jAtCp8gCLalUtFTHKkp7AZwFuQduKXl/KUkEudBU6byQHBninJoyY5zMUILfrQ27dfgMHwS9qZ/7VS5OnQ/yQHrG5CoHXZK43vQ5xzuK5ex+bJhuO6ERnZFoOucrUCjolbdi+5aIIrl+oWlN3nGWCmIL4m9bzXnvGvXdJ84QpOT5dJeuyhD4U6N8If27vVnWlZ6V/0PKmtAOnAHGEhEOuanXsn1QFGMECxpIqePwhYjotR2BVfBkDmwd4=
  bucket: howell-io
  local-dir: _site
  acl: public_read
  on:
    repo: dehowell/dehowell.github.io
