# Site Information
source                : src

title                 : howell.io
tagline               : As unprincipled as the gods, and as much a jack-of-all-trades.
description           : ''
url                   : "http://www.howell.io"
timezone              : "America/New_York"

# Author
author:
  name                : 'David Howell'
  url                 : https://twitter.com/dehowell

# Integrations
google_analytics_id   : 'UA-72069603-1'

# Jekyll Configuration
permalink             : pretty
markdown              : kramdown
kramdown:
  input               : GFM
highlighter           : rouge
exclude:
  - vendor
  - script
  - README.md
  - LICENSE.md
  - Gemfile*

# Jekyll Plugins
gems:
  - jekyll-paginate

# Plugin Configuration: Pagination
paginate              : 5
