# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

gems:
  - jekyll-paginate

# Setup
title:            howell.io
tagline:          'A digital commonplace book; a place to think in public.'
description:      ''
url:              http://www.howell.io
timezone:         America/New_York

author:
  name:           'David Howell'
  url:            https://twitter.com/dehowell

paginate:         5

# Custom vars
google_analytics_id:  'UA-72069603-1'

# Octopress settings
post_ext: md
post_template: post

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      mathjax: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      in_sidebar: false
      mathjax: false

exclude:
- vendor
- script
- README.md
- LICENSE.md
- Gemfile*
