# Site Information
title                 : howell.io
tagline               : 'A digital commonplace book; a place to think in public.'
description           : ''
url                   : "http://www.howell.io"
timezone              : "America/New_York"

# Author
author:
  name                : 'David Howell'
  url                 : https://twitter.com/dehowell

# Integrations
google_analytics_id   : 'UA-72069603-1'

# Jekyll Configuration
permalink             : pretty
lsi                   : false
future                : false
show_drafts           : false
markdown              : kramdown
kramdown:
  input               : GFM
highlighter           : rouge
include:
  - _pages
exclude:
  - vendor
  - script
  - README.md
  - LICENSE.md
  - Gemfile*

# Jekyll Plugins
gems:
  - jekyll-paginate


defaults:
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: post
      category: articles
